services:
        
  zed:
    image: husarion/zed-desktop:humble
    container_name: zed
    network_mode: host
    runtime: nvidia
    tty: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display,video
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./params:/ros_ws/src/zed-ros-wrapper/zed_wrapper/params
    privileged: true
    command: ros2 launch zed_wrapper zed2.launch.py

  rviz:
    image: husarion/rviz2:humble
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
