services:
        
  zed:
    image: husarion/zed-jetson:melodic
    container_name: zed
    network_mode: host
    runtime: nvidia
    tty: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display,video
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - workspace:/ros_ws
      - ./params_l4t32:/ros_ws/src/zed-ros-wrapper/zed_wrapper/params
    privileged: true
    command: roslaunch zed_wrapper <camera_model>.launch

  rviz:
    image: husarion/rviz:noetic
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
    command: rosrun rviz rviz -d /default.rviz

volumes:
  workspace: