services:
  zed:
    image: ${ZED_IMAGE}
    container_name: zed
    network_mode: host
    ipc: host
    runtime: nvidia
    volumes:
      - ./params:/ros2_ws/src/zed-ros-wrapper/zed_wrapper/params
      - /dev/shm:/dev/shm
      - /tmp/zed_ai/:/usr/local/zed/resources/ # Configuration files for quick start
      - /tmp/argus_socket:/tmp/argus_socket
    privileged: true
    command: >
      ros2 launch zed_wrapper zed_camera.launch.py
      camera_model:=${CAMERA_MODEL}

  rviz:
    image: husarion/rviz2:humble
    container_name: rviz2
    network_mode: host
    ipc: host
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
