services:
        
  zed:
    image: ${ZED_IMAGE}
    container_name: zed
    network_mode: host
    runtime: nvidia
    tty: true
    volumes:
      - ./params:/ros_ws/src/zed-ros-wrapper/zed_wrapper/params
      - -/dev/shm:/dev/shm
      - /tmp/zed_ai/:/usr/local/zed/resources/
    privileged: true
    command: ros2 launch zed_wrapper ${CAMERA_MODEL}.launch.py

  rviz:
    image: husarion/rviz2:humble
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
      - /tmp/zed_ai/:/usr/local/zed/resources/
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1