name: Build Docker for Jetson Nano

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Type Dockerfile name inside the repo"
        type: string
        default: "Dockerfile.jetson_l4t32"
      target_release:
        description: "Specify the ZED SDK version of the existing docker image"
        type: string
        default: "4.0.0"

jobs:
  build-and-push:
    runs-on: jetson

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set SHORT_DATE env
        run: echo "SHORT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Echo variable:
        run: echo "Repository ${{ github.repository }} \n ENV
        shell: 

      - name: Build and Push Docker image
        run: |
          docker build -t zed ${{ github.repository }}/${{ github.ref }}/${{ inputs.dockerfile }}
          
          docker tag zed husarion/zed-jetson:melodic
          docker tag zed husarion/zed-jetson:melodic-nightly
          docker tag zed husarion/zed-jetson:melodic-${{ inputs.target_release }}
          docker tag zed husarion/zed-jetson:melodic-${{ inputs.target_release }}-${{ env.SHORT_DATE }}
          docker tag zed husarion/zed-jetson:melodic-${{ inputs.target_release }}-${{ env.SHORT_DATE }}-stable
        
          docker push husarion/zed-jetson:melodic
          docker push husarion/zed-jetson:melodic-nightly
          docker push husarion/zed-jetson:melodic-${{ inputs.target_release }}
          docker push husarion/zed-jetson:melodic-${{ inputs.target_release }}-${{ env.SHORT_DATE }}
          docker push husarion/zed-jetson:melodic-${{ inputs.target_release }}-${{ env.SHORT_DATE }}-stable
