name: Build/Publish ROS Docker Image 

on: 
  workflow_dispatch:
    inputs:
      build_type:
        description: "Is it a \"development\" or a \"stable\" release?"
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - stable
      target_distro:
        description: "In case of \"stable\" release specify the ROS distro of the existing docker image (eg. humble)"
        type: string
        default: "ardent"
      target_release:
        description: "In case of \"stable\" release specify the version of the existing docker image (eg. 1.0.12)"
        type: string
        default: "0.0.0"
      target_date:
        description: "In case of \"stable\" release specify the date of the existing docker image in format YYYYMMDD (eg. 20220124)"
        type: string
        default: "20131206"
  repository_dispatch:
    types: [rebuild]
  pull_request:
    types:
      - closed
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the ZED Docker image
      run: docker build . --file Dockerfile.zed --tag zed:$(date +%s)

    - name: Build the ZED Jetson Docker image
      run: docker build . --file Dockerfile.zed_jetson --tag zed:$(date +%s)

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/husarion