name: Build/Publish ROS Docker Image 

on: 
  workflow_dispatch:
    inputs:
      build_type:
        description: "Is it a \"development\" or a \"stable\" release?"
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - stable
      dockerfile:
        description: "Select Dockerfile"
        required: true
        default: 'Dockerfile.zed'
        type: choice
        options:
          - Dockerfile.zed
          - Dockerfile.zed_jetson
      platform: "Select Platform"
        required: true
        default: 'linux/amd64'
        type: choice
        options:
          - linux/amd64
          - linux/arm64
      target_distro:
        description: "In case of \"stable\" release specify the ROS distro of the existing docker image (eg. humble)"
        type: string
        default: "ardent"
      target_release:
        description: "In case of \"stable\" release specify the version of the existing docker image (eg. 1.0.12)"
        type: string
        default: "0.0.0"
      target_date:
        description: "In case of \"stable\" release specify the date of the existing docker image in format YYYYMMDD (eg. 20220124)"
        type: string
        default: "20131206"
  repository_dispatch:
    types: [rebuild]
  pull_request:
    types:
      - closed
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: husarion-ci/ros-docker-img-action@v0.4
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token:  ${{ secrets.DOCKERHUB_TOKEN }}
          main_branch_name: ros
          dockerfile: ${{ inputs.dockerfile }}
          build_type: ${{ inputs.build_type }}
          ros_distro: noetic
          platforms: ${{ inputs.build_type }}
          # variables important only for stable release
          target_distro: ${{ inputs.target_distro }}
          target_release: ${{ inputs.target_release }}
          target_date: ${{ inputs.target_date }}
