name: Push builded Docker image

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Type Dockerfile name inside the repo"
        type: string
        default: "Dockerfile.jetson_l4t32"
      repo_name:
        description: "Type DockerHub repository name"
        type: string
        default: "zed-jetson"
      ros_distro:
        description: "Type ROS distribution"
        type: string
        default: "melodic"

jobs:
  build-and-push:
    runs-on: jetson

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set SHORT_DATE env
        run: echo "SHORT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Echo variable:
        run: echo "Repository ${{ github.repository }} \n ENV
        shell: 

      - name: Build and Push Docker image
        run: |
          docker build -t zed ${{ github.repository }}/${{ github.ref }}/${{ inputs.dockerfile }}
          
          docker tag zed husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}
          docker tag zed husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-nightly
          docker tag zed husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-3.5.0
          docker tag zed husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-3.5.0-${{ env.SHORT_DATE }}
          docker tag zed husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-3.5.0-${{ env.SHORT_DATE }}-stable
        
          docker push husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}
          docker push husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-nightly
          docker push husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-3.5.0
          docker push husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-3.5.0-${{ env.SHORT_DATE }}
          docker push husarion/${{ inputs.repo_name }}:${{ inputs.ros_distro }}-3.5.0-${{ env.SHORT_DATE }}-stable
