name: Push builded Docker image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Type Docker image name to push"
        type: string
        default: "zed_image:latest"


jobs:
  build-and-push:
    runs-on: jetson

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker tag ${{ inputs.image_name }} husarion/zed_jetson:melodic
          docker tag ${{ inputs.image_name }} husarion/zed_jetson:melodic-nightly
          docker tag ${{ inputs.image_name }} husarion/zed_jetson:melodic-3.5.0
          docker tag ${{ inputs.image_name }} husarion/zed_jetson:melodic-3.5.0-20230517
          docker tag ${{ inputs.image_name }} husarion/zed_jetson:melodic-3.5.0-20230517-stable
        
          docker image push husarion/zed_jetson:melodic
          docker image push husarion/zed_jetson:melodic-nightly
          docker image push husarion/zed_jetson:melodic-3.5.0
          docker image push husarion/zed_jetson:melodic-3.5.0-20230517
          docker image push husarion/zed_jetson:melodic-3.5.0-20230517-stable
